name: Dominion
main: com.pico52.dominion.Dominion
version: 0.4.1
author: Pico52
commands:
  dominion:
    aliases: [dom, d]
    description: This is for all users to manage their settlements, buildings, units, and spells.
    usage: /<command> [info / storage / withdraw / deposit / list / listmy / destroy / employ / employment / data / production / train / attack / move / camp / drop / pickup / holding / disband]
    permission: dominion
    permission-message: You don't have <permission>.
  admindominion:
    aliases: [admind, admindom, ad, adom, adominion, dadmin, domadmin, dominionadmin]
    description: This is used for administrators to control game functions.
    usage: /<command> [setmaterial / add / subtract / build / create / kill / remove / setowner / setbiome / update / manualupdate]
    permission: admindominion
    permission-message: You don't have <permission>.
permissions:
  dominion:
    description:  This is for all users to manage their settlements.
    default: true
  admindominion:
    description:  This is used for administrators to control mod functions.
    default: op